networks:
  transactions-network:
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:4.0.6-management
    container_name: 'rabbitmq'
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - transactions-network
